#!/usr/bin/env node
/**
 * Unit tests for locationImageBuilderCore.ts and locationImageTracker.ts
 * Requires: npm run compile
 */
const { buildLocationImagePromptCore } = require('../out/locationImageBuilderCore');
const {
    shouldAutoGenerateForLocation,
    markLocationAutoGenerated,
    resetLocationImageTracker
} = require('../out/locationImageTracker');

let failed = 0;

function fail(msg) {
    console.error(`FAIL: ${msg}`);
    failed++;
}

function ok(msg) {
    console.log(`OK: ${msg}`);
}

const sampleForge = {
    format: 'lorerelay-world-forge/1.0',
    meta: { worldName: 'Test World', theme: 'dungeon-crawler' },
    geography: {
        regions: [{
            id: 'upper_catacombs',
            name: 'Upper Catacombs',
            type: 'dungeon',
            dangerLevel: 3,
            imagePromptHint: 'stone corridors, torches'
        }],
        locations: [{
            id: 'entrance_hall',
            name: 'Entrance Hall',
            regionId: 'upper_catacombs',
            type: 'landmark',
            factionControl: 'grave_watchers',
            description: 'A smoky entrance hall.'
        }]
    },
    factions: [{
        id: 'grave_watchers',
        name: 'Grave Watchers',
        type: 'neutral',
        power: 40
    }],
    loreHistory: [],
    initialNpcs: []
};

const liveState = {
    format: 'lorerelay-world-state/1.0',
    worldTurn: 5,
    factions: {},
    regions: {
        upper_catacombs: { dangerLevel: 9, controllingFaction: 'grave_watchers' }
    }
};

// --- buildLocationImagePromptCore ---

{
    const prompt = buildLocationImagePromptCore(sampleForge, 'entrance_hall');
    if (!prompt) { fail('returns non-empty prompt'); } else { ok('returns non-empty prompt'); }
    if (!prompt.includes('stone corridors')) { fail('includes region hint'); } else { ok('includes region hint'); }
    if (!prompt.includes('Entrance Hall')) { fail('includes location name'); } else { ok('includes location name'); }
    if (!prompt.includes('dungeon-crawler')) { fail('includes theme'); } else { ok('includes theme'); }
}

{
    const prompt = buildLocationImagePromptCore(sampleForge, 'entrance_hall', liveState);
    if (!prompt.includes('dangerous atmosphere')) { fail('live danger >= 7 adds ominous tag'); } else { ok('live danger >= 7 adds ominous tag'); }
}

{
    const prompt = buildLocationImagePromptCore(sampleForge, 'entrance_hall', liveState, { includeDanger: false });
    if (prompt.includes('dangerous atmosphere')) { fail('includeDanger:false skips danger tags'); } else { ok('includeDanger:false skips danger tags'); }
}

{
    const prompt = buildLocationImagePromptCore(sampleForge, 'entrance_hall', undefined, { includeFaction: false });
    if (prompt.includes('Grave Watchers')) { fail('includeFaction:false skips faction'); } else { ok('includeFaction:false skips faction'); }
}

{
    const prompt = buildLocationImagePromptCore(sampleForge, 'nonexistent');
    if (prompt !== '') { fail('unknown location returns empty string'); } else { ok('unknown location returns empty string'); }
}

// --- locationImageTracker ---

{
    resetLocationImageTracker();
    if (!shouldAutoGenerateForLocation('entrance_hall')) { fail('first request allowed'); } else { ok('first request allowed'); }
    markLocationAutoGenerated('entrance_hall');
    if (shouldAutoGenerateForLocation('entrance_hall')) { fail('same location blocked immediately'); } else { ok('same location blocked immediately'); }
    if (!shouldAutoGenerateForLocation('archive_room')) { fail('different location allowed'); } else { ok('different location allowed'); }
    resetLocationImageTracker();
}

if (failed > 0) {
    process.exit(1);
}
console.log('All location image builder tests passed.');