#!/usr/bin/env node
'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const source = `${fs.readFileSync(path.join(__dirname, '..', 'webview/modules/85b4-logistics-navigation.js'), 'utf8')}\nglobalThis.api={computeLogisticsMinimapModel,logisticsMinimapCameraAt,computeLogisticsSemanticZoom,computeLogisticsFilterModel};`;
const context = { globalThis: {}, Map, Set, Number, String, Array, Object, Math, Intl }; context.globalThis = context;
vm.runInNewContext(source, context); const api = context.api;
const nodes = [{ id: 'a', label: 'Ａｌｐｈａ', x: -50, y: 10 }, { id: 'b', label: 'Beta', x: 250, y: 120 }];
const regions = new Map([['r', { x: -60, y: 0, w: 330, h: 150 }]]);
const camera = { k: 1, tx: 20, ty: -10 };
const model = api.computeLogisticsMinimapModel({ graphBounds: { minX: -60, minY: 0, maxX: 270, maxY: 150 }, viewportSize: { width: 300, height: 200 }, camera, nodes, regions });
assert.ok(Number.isFinite(model.scale) && model.scale > 0, '1 minimap scale finite');
assert.ok(model.contentRect.w <= 132 && model.contentRect.h <= 132, '2 content fits');
assert.ok(Number.isFinite(api.computeLogisticsMinimapModel({ viewportSize: { width: 0, height: 0 } }).viewportRect.w), '3 zero viewport safe');
assert.ok(api.computeLogisticsMinimapModel({ nodes: [] }).nodeMarkers.length === 0, '4 empty graph safe');
assert.strictEqual(model.regionRects.length, 1, '5 regions project');
assert.strictEqual(model.nodeMarkers.length, 2, '6 nodes project');
const panned = api.computeLogisticsMinimapModel({ graphBounds: model.worldBounds, viewportSize: { width: 300, height: 200 }, camera: { ...camera, tx: 60 }, nodes, regions });
assert.notStrictEqual(panned.viewportRect.x, model.viewportRect.x, '7 pan moves viewport rect');
const zoomed = api.computeLogisticsMinimapModel({ graphBounds: model.worldBounds, viewportSize: { width: 300, height: 200 }, camera: { ...camera, k: 2 }, nodes, regions });
assert.ok(zoomed.viewportRect.w < model.viewportRect.w, '8 zoom shrinks viewport rect');
const next = api.logisticsMinimapCameraAt(model, { x: 66, y: 66 }, { width: 300, height: 200 }, camera);
assert.strictEqual(next.k, camera.k, '9 minimap pan preserves scale');
assert.ok(Number.isFinite(next.tx) && Number.isFinite(next.ty), '10 minimap click camera finite');
assert.strictEqual(api.computeLogisticsSemanticZoom({ cameraScale: 0.4 }).level, 'overview', '11 overview level');
assert.strictEqual(api.computeLogisticsSemanticZoom({ cameraScale: 0.8 }).level, 'standard', '12 standard level');
assert.strictEqual(api.computeLogisticsSemanticZoom({ cameraScale: 1.3 }).level, 'detail', '13 detail level');
assert.strictEqual(api.computeLogisticsSemanticZoom({ cameraScale: 0.55, options: { previousLevel: 'overview' } }).level, 'overview', '14 overview hysteresis');
const filtered = api.computeLogisticsFilterModel({ nodes: [{ id: 'a', label: 'Ａｌｐｈａ' }, { id: 'b', label: 'Beta' }], routes: [{ id: 'r', fromNodeId: 'a', toNodeId: 'b', commodityId: 'grain', status: 'open' }], commodities: [{ id: 'grain', name: 'Grain' }], query: 'alpha', statusKeys: ['open'] });
assert.strictEqual(filtered.routeMatchKinds.get('r'), 'primary', '15 Unicode normalized search');
assert.strictEqual(filtered.matchCount, 1, '16 factual status filter');
assert.strictEqual(api.computeLogisticsFilterModel({ routes: [], query: '   ' }).active, false, '17 empty query restores normal');
const statusOnly = api.computeLogisticsFilterModel({ nodes: [{ id: 'a', label: 'Alpha' }, { id: 'b', label: 'Beta' }, { id: 'c', label: 'Gamma' }], routes: [{ id: 'r', fromNodeId: 'a', toNodeId: 'b', status: 'blocked' }], statusKeys: ['blocked'] });
assert.strictEqual(statusOnly.nodeMatchKinds.get('c'), 'unrelated', '18 status-only filtering dims a disconnected node');
console.log('logistics navigation: 18 pure contracts passed.');
