import * as fs from 'fs';
import * as vscode from 'vscode';
import { isValidEventId } from './worldEventLogCore';
import { buildLocationImagePrompt } from './locationImageBuilder';
import { loadImageGenConfig } from './imageGenConfig';
import { enqueueImageGeneration, getResolvedImageMode } from './imageGenRunner';
import { markLocationAutoGenerated } from './locationImageTracker';
import { loadWorldForge } from './worldForge';
import { isWorldStateEnabled, loadWorldState } from './worldState';
import { commitGameState } from './stateManager';
import type { GameStateWorld } from './types/GameState';
import { buildAutoImageWorldTrackingPatch } from './autoLocationImageCore';
import { getGameStatePath, getWorkspacePath } from './workspacePaths';

let getPanelRef: (() => vscode.WebviewPanel | undefined) | undefined;

export function initAutoLocationImageRunner(deps: {
    getPanel: () => vscode.WebviewPanel | undefined;
}): void {
    getPanelRef = deps.getPanel;
}

function persistAutoImageTracking(locationId: string, gmTurn: number): void {
    const statePath = getGameStatePath();
    if (!statePath || !fs.existsSync(statePath)) { return; }
    try {
        const state = JSON.parse(fs.readFileSync(statePath, 'utf-8')) as Record<string, unknown>;
        const world = buildAutoImageWorldTrackingPatch(
            state.world as GameStateWorld | undefined,
            locationId,
            gmTurn
        );
        commitGameState({ ...state, world });
    } catch (e) {
        console.error('[autoLocationImage] Failed to persist tracking fields', e);
    }
}

/**
 * Silent auto-queue (no toasts). Posts webview gen start/end only.
 * Returns true when the job was enqueued.
 */
export function queueAutoLocationImageSilent(locationId: string, gmTurn: number): boolean {
    const trimmed = locationId.trim();
    if (!trimmed || !isValidEventId(trimmed)) { return false; }

    const forge = loadWorldForge();
    if (!forge) { return false; }

    const worldState = isWorldStateEnabled() ? loadWorldState() : undefined;
    const prompt = buildLocationImagePrompt(forge, trimmed, worldState);
    if (!prompt) { return false; }

    const panel = getPanelRef?.();
    panel?.webview.postMessage({ type: 'locationImageGenStart', locationId: trimmed });

    const mode = getResolvedImageMode();
    const queued = enqueueImageGeneration(prompt, mode, `loc:${trimmed}`);
    if (!queued) {
        panel?.webview.postMessage({ type: 'locationImageGenEnd', success: false, locationId: trimmed });
        return false;
    }

    markLocationAutoGenerated(trimmed);
    persistAutoImageTracking(trimmed, gmTurn);
    return true;
}

