import * as assert from 'node:assert/strict'; import { test } from 'node:test';
import { applyLoadoutsToBattleSpec, buildAbilityOptions, defaultCombatLoadoutState, formatMechanicsReceipt, mechanicsDisplayModel, normalizeCombatLoadoutState } from './combatLoadoutUiCore';
import { AbilityDefinition, StatusDefinition } from './combatAbilityTypes';
const status: StatusDefinition = { id:'poison',statusClass:'dot',buildupThreshold:100,durationSeconds:8,stacking:'refresh',cureChannels:['cleanse'],tags:[] };
const ability: AbilityDefinition = { id:'hit',name:'Hit',tier:'normal',delivery:{shape:'single_target',range:1,maxTargets:1,falloff:1,dodgeable:true,blockedByCover:false,pierces:false},effects:[{kind:'damage',vector:'physical',penetration:{barrier:'passes',armor:'passes',requiresBodyContact:false,requiresDamageDealt:false},targetRequirement:[],magnitude:1}],auto:{cooldown:1,gambitTags:[]},scaleBehavior:{individual:'full',huge:'full',squad:'full',fleet:'full'},counters:['armor'],tags:[] };
const spec: any={activePreset:'x',deltaSeconds:1,viewport:{width:1,height:1},participantOrder:['a'],initialState:{units:{allies:[{name:'a'}],enemies:[]}}};
test('loadout defaults to legacy and never passes mechanics data',()=>{assert.equal(normalizeCombatLoadoutState(undefined).mode,'legacy_gambit');assert.equal(applyLoadoutsToBattleSpec(spec,defaultCombatLoadoutState(),[ability],[status]).mechanics,undefined);});
test('valid abilities are selectable and selected abilities reach BattleSpec deterministically',()=>{assert.equal(buildAbilityOptions([ability],[status])[0].selectable,true);const state={mode:'mechanics_v1' as const,loadouts:{a:{normalAttackAbilityId:'hit'}}};assert.deepEqual(applyLoadoutsToBattleSpec(spec,state,[ability],[status]),applyLoadoutsToBattleSpec(spec,state,[ability],[status]));assert.equal((applyLoadoutsToBattleSpec(spec,state,[ability],[status]).initialState.units.allies[0] as any).normalAttackAbility.id,'hit');});
test('invalid abilities are disabled and mechanics display is human-readable',()=>{const bad={...ability,counters:[]};assert.equal(buildAbilityOptions([bad],[status])[0].selectable,false);const view=mechanicsDisplayModel({id:'a',hp:4,maxHp:10,attack:1,defense:1,barrier:{amount:3,blocksVectors:[],blocksStatusApplication:true},statuses:[{id:'heal_block',remainingSeconds:2,intensity:1}],buildup:{poison:{value:25,procCount:0,idleSeconds:0}},subsystems:[{tag:'sensor',hp:1,maxHp:1,disabledSeconds:2}]},[{stage:'scale',kind:'subsystem_disabled',subsystemTag:'sensor'}]);assert.equal(view.healBlocked,true);assert.match(view.receipts[0],/sensor/);assert.match(formatMechanicsReceipt({stage:'x',kind:'barrier_absorbed',amount:3}),/Barrier/);});
