import * as assert from 'node:assert/strict';
import { test, describe } from 'node:test';
import { AbilityDefinition, StatusDefinition } from './combatAbilityTypes';
import { advanceMechanicsState, canAct, canMove, MechanicsCombatant, resolveMechanics } from './combatMechanicsResolver';

const statuses: StatusDefinition[] = ['poison','burn','bleed','sleep','paralysis','stun','regen','heal_block'].map(id => ({ id, statusClass: id === 'paralysis' || id === 'stun' || id === 'sleep' ? 'hard_control' : id === 'regen' ? 'beneficial' : 'dot', buildupThreshold: 100, durationSeconds: id === 'sleep' ? 6 : 4, stacking: 'refresh', cureChannels: ['cleanse','time'], tags: [] }));
const ability = (effects: AbilityDefinition['effects'], shape: AbilityDefinition['delivery']['shape'] = 'single_target'): AbilityDefinition => ({ id:'test', name:'Test', tier:'normal', delivery:{shape,range:1,maxTargets:1,falloff:1,dodgeable:true,blockedByCover:false,pierces:false}, effects, auto:{cooldown:1,gambitTags:[]}, scaleBehavior:{individual:'full',huge:'full',squad:'full',fleet:'full'}, counters:['counter'],tags:[] });
// Neutral profile: armour applies normally ('blocked'). 'passes' is the armour-ignoring mode and is
// asserted separately in combatMechanicsCorrectness.test.ts now that penetration.armor is honoured.
const pen = (body = false, damage = false) => ({ barrier:'passes' as const, armor:'blocked' as const, requiresBodyContact:body, requiresDamageDealt:damage });
const actor: MechanicsCombatant = { id:'a',hp:100,maxHp:100,attack:14,defense:0 };
const target = (): MechanicsCombatant => ({ id:'t',hp:100,maxHp:100,attack:1,defense:5,tags:['living'],statuses:[],buildup:{} });

describe('Combat Mechanics Resolver V1', () => {
 test('neutral values reduce exactly to legacy damage', () => { const out=resolveMechanics({ability:ability([{kind:'damage',vector:'physical',penetration:pen(),targetRequirement:[],magnitude:14}]),attacker:actor,target:target(),statuses}); assert.equal(out.damageDealt, Math.max(1,14-5)); });
 test('uses a deterministic fourth-hit evasion counter', () => { let t: MechanicsCombatant={...target(),evasion:25}; for(let i=0;i<3;i++) t=resolveMechanics({ability:ability([{kind:'damage',vector:'physical',penetration:pen(),targetRequirement:[],magnitude:14}]),attacker:actor,target:t,statuses}).target; const fourth=resolveMechanics({ability:ability([{kind:'damage',vector:'physical',penetration:pen(),targetRequirement:[],magnitude:14}]),attacker:actor,target:t,statuses}); assert.equal(fourth.dodged,true); });
 test('orders barrier, armor, resistance and damage', () => { const t: MechanicsCombatant={...target(),defense:4,resistances:{physical:50},barrier:{amount:3,blocksVectors:['physical'],blocksStatusApplication:true}}; const a=ability([{kind:'damage',vector:'physical',penetration:{...pen(),barrier:'consumed'},targetRequirement:[],magnitude:14}]); const out=resolveMechanics({ability:a,attacker:{...actor,attack:14},target:t,statuses}); assert.equal(out.damageDealt,2); assert.equal(out.target.barrier!.amount,0); });
 test('requires body contact for poison and HP damage for bleed', () => { const poison=ability([{kind:'buildup',vector:'biological',penetration:pen(true),targetRequirement:['living'],magnitude:25,statusId:'poison'}]); assert.equal(resolveMechanics({ability:poison,attacker:actor,target:{...target(),tags:['construct']},statuses}).target.buildup?.poison,undefined); const bleed=ability([{kind:'buildup',vector:'physical',penetration:pen(true,true),targetRequirement:['living'],magnitude:25,statusId:'bleed'}]); assert.equal(resolveMechanics({ability:bleed,attacker:actor,target:target(),statuses}).target.buildup?.bleed,undefined); });
 test('procs buildup on fourth hit, escalates threshold, and decays', () => { const a=ability([{kind:'buildup',vector:'biological',penetration:pen(true),targetRequirement:['living'],magnitude:25,statusId:'poison'}]); let t=target(); for(let i=0;i<4;i++) t=resolveMechanics({ability:a,attacker:actor,target:t,statuses}).target; assert.equal(t.statuses?.[0].id,'poison'); assert.equal(t.buildup?.poison.procCount,1); t.buildup!.poison.value=50;t.buildup!.poison.idleSeconds=2; assert.equal(advanceMechanicsState(t,1).buildup!.poison.value,40); });
 test('breaks sleep on damage; paralysis blocks movement but not actions', () => { const t={...target(),statuses:[{id:'sleep',remainingSeconds:6,intensity:1}]}; const out=resolveMechanics({ability:ability([{kind:'damage',vector:'physical',penetration:pen(),targetRequirement:[],magnitude:14}]),attacker:actor,target:t,statuses}); assert.ok(!out.target.statuses?.some(s=>s.id==='sleep')); const p={...target(),statuses:[{id:'paralysis',remainingSeconds:4,intensity:1}]};assert.equal(canMove(p),false);assert.equal(canAct(p),true); });
 test('applies heal block, cleanse, subsystem control, lethality, and is reproducible', () => { const heal=ability([{kind:'heal',vector:'magical',penetration:pen(),targetRequirement:[],magnitude:20}]); const blocked=resolveMechanics({ability:heal,attacker:actor,target:{...target(),hp:50,statuses:[{id:'heal_block',remainingSeconds:4,intensity:1}]},statuses});assert.equal(blocked.target.hp,55); const clean=resolveMechanics({ability:ability([{kind:'cleanse',vector:'magical',penetration:pen(),targetRequirement:[],magnitude:1}]),attacker:actor,target:{...target(),statuses:[{id:'poison',remainingSeconds:4,intensity:1}],buildup:{poison:{value:50,procCount:0,idleSeconds:0}}},statuses});assert.equal(clean.target.statuses?.length,0); const cc=ability([{kind:'buildup',vector:'magical',penetration:pen(),targetRequirement:['colossal'],magnitude:40,statusId:'stun'}]);cc.scaleBehavior={individual:'full',huge:'convert_subsystem',hugeSubsystemTags:['sensor'],squad:'drop',fleet:'drop'}; const huge: MechanicsCombatant={...target(),structureClass:'capital',tags:['colossal'],subsystems:[{tag:'sensor',hp:10,maxHp:10,disabledSeconds:0}]};assert.equal(resolveMechanics({ability:cc,attacker:actor,target:huge,statuses}).target.subsystems![0].disabledSeconds,4); const lethal=resolveMechanics({ability:ability([{kind:'damage',vector:'physical',penetration:pen(),targetRequirement:[],magnitude:14}]),attacker:{...actor,attack:200},target:{...target(),hp:5,lethality:{endureCharges:1,undyingSeconds:0}},statuses});assert.equal(lethal.target.hp,1);assert.deepEqual(resolveMechanics({ability:heal,attacker:actor,target:target(),statuses}),resolveMechanics({ability:heal,attacker:actor,target:target(),statuses})); });
});
