import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import type { GameEntry, GameState, HiddenDiceEntry, ProfileUpdate, SceneSprite } from './types/GameState';
import { applyNpcMemoryUpdates, parseNpcMemoryUpdatesFromGameState } from './npcRegistry';
import { loadGameRules } from './gameRules';
import { isValidEntryId } from './entryId';
import { validateGameState } from './validateGameState';
import { salvageGameStateFromUnknown } from './gameStateSanitize';
import { migrateGameState, CURRENT_SCHEMA_VERSION } from './migrateGameState';
import { getActiveWorkspaceFolder, writeJsonAtomic } from './workspacePaths';

export interface GameStateSyncDeps {
    getPanel(): vscode.WebviewPanel | undefined;
    getGameStatePath(): string | undefined;
    getWorkspacePath(): string | undefined;
    getSkillDir(): string | undefined;
    getHistoryPath(): string | undefined;
    processProfileUpdates(updates: ProfileUpdate[]): void;
    maybeSuggestArchive(): void;
    appendGmBridgeLog(line: string): void;
}

let deps: GameStateSyncDeps | undefined;

function buildNpcTrustLookup(): NpcTrustLookup {
    if (!loadGameRules().enableNpcRegistry) {
        return { readTrust: () => readNpcPlayerTrust(undefined) };
    }
    const registry = loadNpcRegistry();
    return {
        readTrust(npcId: string) {
            return readNpcPlayerTrust(registry.npcs[npcId]?.disposition?.playerTrust);
        },
    };
}

let gameEntryHistory: GameEntry[] = [];
const seenEntryIds = new Set<string>();
let schemaWarningShown = false;
let lastGoodGameState: Record<string, unknown> | undefined;
let gameStateSyncSeq = 0;
import { processTurnResult, takeAutoLocationImageRequest } from './statePatch';
import {
    ensureAcceptedTurnWriterLease,
    preflightAcceptedTurn,
    runAcceptedTurnSingleFlight,
} from './acceptedTurnReplayGuard';
import type { TurnResultFileOutcome } from './acceptedTurnReplayGuardCore';
import { queueAutoLocationImageSilent } from './autoLocationImageRunner';
import { markTurnResultHandled } from './turnResultFallback';
import { handleGameStateMedia, handleTurnResultMedia } from './mediaAgent';
import { pushGameStateToRemoteClients } from './remotePlayServer';
import { pushScenarioDirectorToWebview } from './scenarioDirector';
import { pushPartyDirectorToWebview } from './partyDirector';
import { pushWorldViewToWebview } from './worldView';
import { maybeTickSimulation } from './emergentSimulator';
import { isAllowedImagePath, toWebviewSafeMediaRef } from './mediaPaths';
import type { TurnResult } from './types/TurnResult';
import { loadWorldForge } from './worldForge';
import { loadWorldState, isWorldStateEnabled } from './worldState';
import { buildLocationImagePrompt } from './locationImageBuilder';
import { shouldAutoGenerateForLocation, markLocationAutoGenerated } from './locationImageTracker';
import { enqueueImageGeneration, getResolvedImageMode } from './imageGenRunner';
import { commitGameState } from './stateManager';
import { scheduleProtagonistBootstrap } from './protagonistBootstrap';
import { loadNpcRegistry } from './npcRegistry';
import { readNpcPlayerTrust, type NpcTrustLookup } from './npcWhereaboutsTrustCore';
import {
    sanitizeGameStateForWebview,
    sanitizeTurnResultForWebview,
} from './gameStateWebviewSanitize';

export { isAllowedImagePath };

let fileWatcher: vscode.FileSystemWatcher | undefined;
let turnResultWatcher: vscode.FileSystemWatcher | undefined;
let debounceTimer: NodeJS.Timeout | undefined;
let lastProcessedTurnHash = '';
/** Entry IDs already seen when applying game_state (for MediaAgent new-entry detection). */
const knownStateEntryIds = new Set<string>();

export function resetTurnResultProcessingStateForTests(): void {
    lastProcessedTurnHash = '';
    knownStateEntryIds.clear();
}

export function getLastProcessedTurnHashForTests(): string {
    return lastProcessedTurnHash;
}

export function initGameStateSync(syncDeps: GameStateSyncDeps): void {
    deps = syncDeps;
}

function requireDeps(): GameStateSyncDeps {
    if (!deps) {
        throw new Error('GameStateSync not initialized — call initGameStateSync() in activate()');
    }
    return deps;
}

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null && !Array.isArray(value);
}

export function isValidGameEntry(value: unknown): value is GameEntry {
    if (!isRecord(value)) {
        return false;
    }
    return (
        isValidEntryId(value.id) &&
        (value.role === 'gm' || value.role === 'user') &&
        typeof value.sender === 'string' &&
        typeof value.content === 'string'
    );
}

export function getGameEntryHistory(): GameEntry[] {
    return gameEntryHistory;
}

/** 最後に検証済みの game_state（ディスク再読み込み回避用）。 */
export function getCachedGameState(): Record<string, unknown> | undefined {
    return lastGoodGameState;
}

export function isGameOverActiveCached(): boolean {
    const state = lastGoodGameState;
    if (!state || typeof state.gameOver !== 'object' || state.gameOver === null) {
        return false;
    }
    return Boolean((state.gameOver as Record<string, unknown>).active);
}

export function setGameEntryHistory(entries: GameEntry[]): void {
    gameEntryHistory = entries;
}

export function getSeenEntryIds(): Set<string> {
    return seenEntryIds;
}

export function syncSeenEntryIdsFromHistory(): void {
    seenEntryIds.clear();
    for (const e of gameEntryHistory) {
        if (e.id) {
            seenEntryIds.add(e.id);
        }
    }
}

/** 履歴配列と seen ID をまとめて更新する（Undo / Rewind / Checkpoint 用）。 */
export function setGameEntryHistoryWithSeenIds(entries: GameEntry[], seenIds?: Iterable<string>): void {
    gameEntryHistory = entries;
    seenEntryIds.clear();
    if (seenIds) {
        for (const id of seenIds) {
            seenEntryIds.add(id);
        }
    } else {
        syncSeenEntryIdsFromHistory();
    }
}

export function loadHistoryFromDisk(): void {
    const d = requireDeps();
    const histPath = d.getHistoryPath();
    if (!histPath || !fs.existsSync(histPath)) {
        return;
    }
    try {
        const entries: GameEntry[] = JSON.parse(fs.readFileSync(histPath, 'utf-8'));
        if (Array.isArray(entries)) {
            for (const e of entries) {
                if (isValidGameEntry(e) && !seenEntryIds.has(e.id)) {
                    seenEntryIds.add(e.id);
                    gameEntryHistory.push(e);
                }
            }
        }
    } catch (e) {
        console.error('Error loading game_history.json:', e);
    }
}

export function saveHistoryToDisk(): void {
    const d = requireDeps();
    const histPath = d.getHistoryPath();
    if (!histPath) {
        return;
    }
    try {
        writeJsonAtomic(histPath, gameEntryHistory, true);
    } catch (e) {
        console.error('Error saving game_history.json:', e);
    }
}

/** Saga アーカイブ後に game_history.json の変更をメモリ上の履歴へ反映する */
export function replaceHistoryFromDisk(): void {
    gameEntryHistory = [];
    seenEntryIds.clear();
    loadHistoryFromDisk();
}

export function safeImageUri(imagePath: string): string | undefined {
    const panel = requireDeps().getPanel();
    if (!imagePath || !isAllowedImagePath(imagePath) || !panel) {
        return undefined;
    }
    return panel.webview.asWebviewUri(vscode.Uri.file(path.normalize(imagePath))).toString();
}

function resolveSpriteForWebview(sprite: SceneSprite | string | undefined): SceneSprite | undefined {
    if (!sprite) {
        return undefined;
    }
    if (typeof sprite === 'string') {
        const uri = safeImageUri(sprite);
        return uri ? { image: uri, position: 'center' } : undefined;
    }
    const out: SceneSprite = { ...sprite };
    if (out.image) {
        const uri = safeImageUri(out.image);
        if (!uri) {
            return undefined;
        }
        out.image = uri;
    }
    return out;
}

export async function sendCurrentState(retryCount = 0, fullHistory = false): Promise<void> {
    const d = requireDeps();
    const statePath = d.getGameStatePath();
    const panel = d.getPanel();
    if (!statePath || !panel) {
        return;
    }

    try {
        if (fs.existsSync(statePath)) {
            const raw = fs.readFileSync(statePath, 'utf-8');
            // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
            let state = JSON.parse(raw);

            // Auto-migrate legacy game_state.json (v1: no schemaVersion field)
            const { state: migratedState, migrated, fromVersion } = migrateGameState(state);
            if (migrated) {
                // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
                state = migratedState;
                try {
                    commitGameState(state);
                    console.log(
                        `[LoreRelay] game_state.json auto-migrated v${fromVersion} → v${CURRENT_SCHEMA_VERSION}`
                    );
                } catch (e) {
                    console.error('[LoreRelay] Failed to save migrated game_state.json:', e);
                }
            }

            const schemaErrors = validateGameState(state);
            let activeState = state as Record<string, unknown>;
            let hadSchemaErrors = false;

            if (schemaErrors.length > 0) {
                const salvaged = salvageGameStateFromUnknown(state);
                const salvageErrors = salvaged ? validateGameState(salvaged) : ['salvage failed'];
                if (salvaged && salvageErrors.length === 0) {
                    activeState = salvaged;
                    state = salvaged;
                    hadSchemaErrors = false;
                    schemaWarningShown = false;
                    const recoveredLine = '[LoreRelay] game_state.json recovered via salvage';
                    console.log(recoveredLine);
                    d.appendGmBridgeLog(recoveredLine);
                    try {
                        commitGameState(salvaged);
                    } catch (e) {
                        console.error('[LoreRelay] Failed to persist salvaged game_state.json:', e);
                    }
                } else {
                    hadSchemaErrors = true;
                    const summary = schemaErrors.join('; ');
                    const logLine = `[LoreRelay] game_state.json schema violation: ${summary}`;
                    console.warn(logLine);
                    d.appendGmBridgeLog(logLine);
                    try {
                        const invalidPath = path.join(path.dirname(statePath), 'game_state.invalid.latest.json');
                        writeJsonAtomic(invalidPath, state);
                    } catch (e) {
                        console.error('Failed to save game_state.invalid.latest.json:', e);
                    }
                    if (!schemaWarningShown) {
                        schemaWarningShown = true;
                        vscode.window.showWarningMessage(
                            'LoreRelay: game_state.json has schema errors — showing last good state. Check "LoreRelay: GM Bridge" output for details.'
                        );
                    }
                    if (lastGoodGameState) {
                        activeState = lastGoodGameState;
                    } else {
                        panel.webview.postMessage({
                            type: 'gameStateUpdate',
                            syncSeq: ++gameStateSyncSeq,
                            schemaErrors
                        });
                        return;
                    }
                }
            } else {
                schemaWarningShown = false;
                
                // --- Location Change Image Generation Hook (legacy imageGen.autoOnLocationChange) ---
                const cartographyAuto = vscode.workspace.getConfiguration('textAdventure.cartography')
                    .get<boolean>('autoLocationImage', false);
                if (!cartographyAuto && lastGoodGameState) {
                    const oldLocationId = isRecord(lastGoodGameState.world)
                        && typeof lastGoodGameState.world.currentLocationId === 'string'
                        ? lastGoodGameState.world.currentLocationId
                        : undefined;
                    const newLocationId = isRecord(activeState.world)
                        && typeof activeState.world.currentLocationId === 'string'
                        ? activeState.world.currentLocationId
                        : undefined;

                    if (oldLocationId && newLocationId && newLocationId !== oldLocationId) {
                        const config = vscode.workspace.getConfiguration('textAdventure.imageGen');
                        if (config.get<boolean>('autoOnLocationChange', false) && shouldAutoGenerateForLocation(newLocationId)) {
                            const forge = loadWorldForge();
                            if (forge) {
                                const worldState = isWorldStateEnabled() ? loadWorldState() : undefined;
                                const prompt = buildLocationImagePrompt(forge, newLocationId, worldState);
                                if (prompt) {
                                    const mode = getResolvedImageMode();
                                    if (enqueueImageGeneration(prompt, mode, `loc:${newLocationId}`)) {
                                        markLocationAutoGenerated(newLocationId);
                                    }
                                }
                            }
                        }
                    }
                }
                // ---------------------------------------------

                lastGoodGameState = JSON.parse(JSON.stringify(activeState)) as Record<string, unknown>;
                try {
                    const goodPath = path.join(path.dirname(statePath), 'last_good_game_state.json');
                    writeJsonAtomic(goodPath, state);
                } catch (e) {
                    console.error('Failed to save last_good_game_state.json:', e);
                }
            }

            if (!hadSchemaErrors && Array.isArray(state.profileUpdates) && state.profileUpdates.length > 0) {
                d.processProfileUpdates(state.profileUpdates as ProfileUpdate[]);
                delete state.profileUpdates;
                commitGameState(state);
            }

            if (!hadSchemaErrors && Array.isArray(state.npcMemoryUpdates) && state.npcMemoryUpdates.length > 0) {
                if (loadGameRules().enableNpcRegistry) {
                    const currentTurn = gameEntryHistory.length;
                    const updates = parseNpcMemoryUpdatesFromGameState(state.npcMemoryUpdates);
                    applyNpcMemoryUpdates(updates, currentTurn);
                }
                delete state.npcMemoryUpdates;
                commitGameState(state);
            }

            let historyUpdated = false;
            if (!hadSchemaErrors && state.entries && Array.isArray(state.entries)) {
                state.entries.forEach((rawEntry: unknown) => {
                    if (!isValidGameEntry(rawEntry)) {
                        return;
                    }
                    const entry = rawEntry;
                    const histIdx = gameEntryHistory.findIndex((e) => e.id === entry.id);
                    if (histIdx >= 0) {
                        const prev = gameEntryHistory[histIdx];
                        const next: GameEntry = { ...prev };
                        let changed = false;
                        const setIfString = (key: keyof Pick<GameEntry, 'role' | 'sender' | 'content' | 'image' | 'imagePrompt' | 'editedAt'>) => {
                            const value = entry[key];
                            if (typeof value === 'string' && value !== next[key]) {
                                (next as any)[key] = value;
                                changed = true;
                            }
                        };
                        setIfString('role');
                        setIfString('sender');
                        setIfString('content');
                        setIfString('image');
                        setIfString('imagePrompt');
                        setIfString('editedAt');
                        if (typeof entry.imageBlocked === 'boolean' && entry.imageBlocked !== next.imageBlocked) {
                            next.imageBlocked = entry.imageBlocked;
                            changed = true;
                        }
                        if (typeof entry.excludedFromPrompt === 'boolean' && entry.excludedFromPrompt !== next.excludedFromPrompt) {
                            next.excludedFromPrompt = entry.excludedFromPrompt;
                            changed = true;
                        }
                        if (typeof entry.speakerNpcId === 'string' && isValidEntryId(entry.speakerNpcId)) {
                            if (entry.speakerNpcId !== next.speakerNpcId) {
                                next.speakerNpcId = entry.speakerNpcId;
                                changed = true;
                            }
                        }
                        if (changed) {
                            gameEntryHistory[histIdx] = next;
                            historyUpdated = true;
                        }
                        return;
                    }
                    if (!seenEntryIds.has(entry.id)) {
                        seenEntryIds.add(entry.id);
                        const entryWithState: Record<string, unknown> = { ...entry };
                        if (entry.role === 'gm') {
                            if (state.status) { entryWithState.status = JSON.parse(JSON.stringify(state.status)); }
                            if (state.options) { entryWithState.options = [...state.options]; }
                            if (state.theme) { entryWithState.theme = state.theme; }
                            if (state.bgm) { entryWithState.bgm = state.bgm; }
                            if (state.mood) { entryWithState.mood = state.mood; }
                            if (state.sfx) { entryWithState.sfx = Array.isArray(state.sfx) ? [...state.sfx] : state.sfx; }
                            if (state.latestImage) { entryWithState.latestImage = state.latestImage; }
                            if (state.background) { entryWithState.background = state.background; }
                            if (state.sprite) {
                                entryWithState.sprite = typeof state.sprite === 'string'
                                    ? state.sprite
                                    : JSON.parse(JSON.stringify(state.sprite));
                            }
                            if (state.summary) { entryWithState.summary = state.summary; }
                            if (state.gameOver) { entryWithState.gameOver = JSON.parse(JSON.stringify(state.gameOver)); }
                        }
                        gameEntryHistory.push(entryWithState as unknown as GameEntry);
                        historyUpdated = true;
                    }
                });
            }
            if (historyUpdated) {
                saveHistoryToDisk();
                d.maybeSuggestArchive();
                // GM ターン数が simIntervalTurns の倍数に達したらシミュレーションを進める
                const gmTurnCount = gameEntryHistory.filter((e) => e.role === 'gm').length;
                maybeTickSimulation(gmTurnCount);
            }

            const currentEntries: GameEntry[] = Array.isArray(activeState.entries)
                ? (activeState.entries as unknown[]).filter(isValidGameEntry)
                : [];
            const sourceEntries: GameEntry[] = fullHistory ? gameEntryHistory : currentEntries;
            const entriesToSend = sourceEntries.map((entry: GameEntry) => {
                const e = { ...entry };
                if (e.image) {
                    const diskPath = e.image;
                    const safeRef = toWebviewSafeMediaRef(diskPath);
                    if (safeRef) {
                        e.rawImagePath = safeRef;
                    } else {
                        delete e.rawImagePath;
                    }
                    const uri = safeImageUri(diskPath);
                    if (uri) {
                        e.image = uri;
                    } else {
                        delete e.image;
                        e.imageBlocked = true;
                    }
                }
                return e;
            });

            const latestImage = activeState.latestImage ? safeImageUri(String(activeState.latestImage)) : undefined;
            const background = activeState.background ? safeImageUri(String(activeState.background)) : undefined;
            const sprite = resolveSpriteForWebview(activeState.sprite as SceneSprite | string | undefined);

            const hiddenDice: HiddenDiceEntry[] | undefined =
                Array.isArray(activeState.hiddenDice)
                    ? (activeState.hiddenDice as unknown[])
                        .filter((dice): dice is Record<string, unknown> =>
                            typeof dice === 'object' && dice !== null && typeof (dice as Record<string, unknown>).notation === 'string'
                        )
                        .map((dice, idx) => ({
                            id: String(dice.id || `hd-${idx}-${dice.notation ?? ''}-${dice.purpose || ''}`),
                            notation: String(dice.notation ?? ''),
                            ...(dice.purpose !== undefined ? { purpose: String(dice.purpose) } : {}),
                        }))
                    : undefined;

            const latestImageRawPath = activeState.latestImage
                ? toWebviewSafeMediaRef(String(activeState.latestImage))
                : undefined;
            const stateForWebview = sanitizeGameStateForWebview({
                ...activeState,
                entries: entriesToSend,
                latestImage,
                latestImageRawPath,
                background,
                sprite,
                hiddenDice,
            });
            panel.webview.postMessage({
                type: 'gameStateUpdate',
                syncSeq: ++gameStateSyncSeq,
                fullHistory,
                state: stateForWebview,
                ...(hadSchemaErrors ? { schemaErrors } : {})
            });

            if (fullHistory) {
                knownStateEntryIds.clear();
                if (Array.isArray(activeState.entries)) {
                    for (const raw of activeState.entries) {
                        if (isValidGameEntry(raw)) {
                            knownStateEntryIds.add(raw.id);
                        }
                    }
                }
            } else if (!hadSchemaErrors) {
                handleGameStateMedia(state as GameState, (entry) => {
                    if (!entry.id || knownStateEntryIds.has(entry.id)) {
                        return false;
                    }
                    knownStateEntryIds.add(entry.id);
                    return true;
                });
            }

            pushGameStateToRemoteClients(activeState as unknown as GameState, gameEntryHistory);
            pushScenarioDirectorToWebview();
            pushPartyDirectorToWebview();
            const worldBlock = (activeState as Record<string, unknown>).world as Record<string, unknown> | undefined;
            pushWorldViewToWebview(typeof worldBlock?.currentLocationId === 'string' ? worldBlock.currentLocationId : undefined);
        }
    } catch (e) {
        console.error(`Error reading game state (attempt ${retryCount + 1}):`, e);
        if (retryCount < 3) {
            setTimeout(() => sendCurrentState(retryCount + 1, fullHistory), 200);
        }
    }
}

/** game_state.json の FileSystemWatcher を開始する（BGM/SE 監視は extension 側）。 */
export function startGameStateWatcher(): void {
    loadHistoryFromDisk();
    void sendCurrentState(0, true);

    if (fileWatcher) {
        fileWatcher.dispose();
    }

    const folder = getActiveWorkspaceFolder();
    if (!folder) {
        return;
    }

    fileWatcher = vscode.workspace.createFileSystemWatcher(
        new vscode.RelativePattern(folder, 'game_state.json')
    );

    const handleChange = () => {
        if (debounceTimer) {
            clearTimeout(debounceTimer);
        }
        debounceTimer = setTimeout(() => {
            void sendCurrentState();
        }, 300);
    };

    fileWatcher.onDidChange(handleChange);
    fileWatcher.onDidCreate(handleChange);

    if (turnResultWatcher) {
        turnResultWatcher.dispose();
    }
    turnResultWatcher = vscode.workspace.createFileSystemWatcher(
        new vscode.RelativePattern(folder, 'turn_result.json')
    );
    const handleTurnResult = (uri: vscode.Uri) => {
        setTimeout(() => { void processTurnResultFileAt(uri.fsPath); }, 50);
    };
    turnResultWatcher.onDidChange(handleTurnResult);
    turnResultWatcher.onDidCreate(handleTurnResult);

    // Sweep for a turn_result.json left over from before this watcher existed
    // (e.g. the extension host restarted mid-turn, or a prior run's watcher
    // missed the write) so a reload alone can recover a stuck turn.
    void processTurnResultFileAt(path.join(folder.uri.fsPath, 'turn_result.json'));
}

function sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Reads turn_result.json at fsPath if present and not already processed
 * (sha256-deduped via lastProcessedTurnHash), applies it, and notifies the
 * webview. Returns a structured outcome so stale duplicates and repair states
 * cannot collapse into the same fallback behavior as a missing file.
 */
async function processTurnResultFileAt(fsPath: string, retryCount = 0): Promise<TurnResultFileOutcome> {
    return runAcceptedTurnSingleFlight(() => processTurnResultFileAtSerialized(fsPath, retryCount));
}

async function processTurnResultFileAtSerialized(fsPath: string, retryCount = 0): Promise<TurnResultFileOutcome> {
    let hash = '';
    let turnResult: TurnResult;
    try {
        if (!fs.existsSync(fsPath)) {
            return { kind: 'missing', accepted: false, reason: 'turn_result.json missing' };
        }
        const content = fs.readFileSync(fsPath, 'utf-8');
        if (!content.trim()) {
            throw new Error('Empty file content');
        }

        hash = crypto.createHash('sha256').update(content, 'utf-8').digest('hex');
        if (hash === lastProcessedTurnHash) {
            return { kind: 'alreadyAccepted', accepted: false, reason: 'same-process duplicate raw hash' };
        }

        turnResult = JSON.parse(content) as TurnResult;
    } catch (e) {
        if (retryCount < 3) {
            console.warn(`Retry reading turn_result.json (attempt ${retryCount + 1}): ${e instanceof Error ? e.message : String(e)}`);
            await sleep(100);
            return processTurnResultFileAtSerialized(fsPath, retryCount + 1);
        }
        console.error('Failed to parse turn_result.json after retries', e);
        return { kind: 'retryableFailure', accepted: false, reason: 'failed to parse turn_result.json after retries' };
    }

    const workspacePath = path.dirname(fsPath);
    const leaseConflict = ensureAcceptedTurnWriterLease(workspacePath, 'turn-result-observation');
    if (leaseConflict) {
        return leaseConflict;
    }

    const preflight = preflightAcceptedTurn(workspacePath, turnResult, hash, 'turn_result_file');
    if (preflight.kind !== 'unseen') {
        if (preflight.kind === 'alreadyAccepted') {
            console.info('[gameStateSync] stale accepted turn_result.json observed; skipping apply', {
                turnId: preflight.turnId,
                identityHash: preflight.identityHash,
            });
        } else {
            console.warn('[gameStateSync] turn_result.json preflight stopped before apply', preflight);
        }
        return preflight;
    }

    const enriched = processTurnResult(turnResult, preflight.context);
    if (!enriched) {
        return {
            kind: 'retryableFailure',
            accepted: false,
            identityHash: preflight.context.identity.identityHash,
            turnId: preflight.context.identity.turnId,
            reason: 'processTurnResult returned false before Accepted boundary',
        };
    }

    lastProcessedTurnHash = hash;
    markTurnResultHandled(enriched);

    try {
        handleTurnResultMedia(enriched);
    } catch (e) {
        console.error('[gameStateSync] Accepted turn media handling failed', e);
    }

    try {
        const panel = deps?.getPanel();
        if (panel) {
            const trustLookup = buildNpcTrustLookup();
            panel.webview.postMessage({
                type: 'gameStateUpdate',
                syncSeq: ++gameStateSyncSeq,
                turnResult: sanitizeTurnResultForWebview(enriched, trustLookup),
            });
        }
    } catch (e) {
        console.error('[gameStateSync] Accepted turn webview update failed', e);
    }

    try {
        const autoImageRequest = takeAutoLocationImageRequest();
        if (autoImageRequest) {
            queueAutoLocationImageSilent(autoImageRequest.locationId, autoImageRequest.gmTurn);
        }
    } catch (e) {
        console.error('[gameStateSync] Accepted auto-location image queue failed', e);
    }

    try {
        scheduleProtagonistBootstrap(enriched);
    } catch (e) {
        console.error('[gameStateSync] Accepted protagonist bootstrap scheduling failed', e);
    }

    return {
        kind: 'newlyAccepted',
        accepted: true,
        identityHash: preflight.context.identity.identityHash,
        turnId: preflight.context.identity.turnId,
    };
}

export async function processTurnResultFileAtForTests(fsPath: string, retryCount = 0): Promise<TurnResultFileOutcome> {
    return processTurnResultFileAt(fsPath, retryCount);
}

/**
 * Fallback safety net for when the turn_result.json FileSystemWatcher doesn't
 * fire in time (observed: first-ever turn_result.json write in a brand-new
 * workspace can outrun the watcher's onDidCreate event). Wired into
 * turnResultFallback.ts via initTurnResultFallback() and called a short delay
 * after the GM bridge process exits. A no-op if the watcher already handled
 * it (sha256 hash dedupe in processTurnResultFileAt above).
 */
export async function checkPendingTurnResultFile(): Promise<TurnResultFileOutcome> {
    const folder = getActiveWorkspaceFolder();
    if (!folder) {
        return { kind: 'missing', accepted: false, reason: 'no workspace folder' };
    }
    return processTurnResultFileAt(path.join(folder.uri.fsPath, 'turn_result.json'));
}

export function disposeGameStateWatcher(): void {
    if (fileWatcher) {
        fileWatcher.dispose();
        fileWatcher = undefined;
    }
    if (turnResultWatcher) {
        turnResultWatcher.dispose();
        turnResultWatcher = undefined;
    }
    if (debounceTimer) {
        clearTimeout(debounceTimer);
        debounceTimer = undefined;
    }
    knownStateEntryIds.clear();
}
