/** 拡張機能メモリ上で location 自動生成の重複・クールダウンを管理（game_state.json は書き換えない）。 */

const AUTO_GEN_COOLDOWN_MS = 60_000;

let lastAutoGenLocationId: string | undefined;
let lastAutoGenAt = 0;

export function shouldAutoGenerateForLocation(locationId: string): boolean {
    if (!locationId) {
        return false;
    }
    const now = Date.now();
    if (lastAutoGenLocationId === locationId && now - lastAutoGenAt < AUTO_GEN_COOLDOWN_MS) {
        return false;
    }
    return lastAutoGenLocationId !== locationId;
}

export function markLocationAutoGenerated(locationId: string): void {
    lastAutoGenLocationId = locationId;
    lastAutoGenAt = Date.now();
}

/** テスト用リセット */
export function resetLocationImageTracker(): void {
    lastAutoGenLocationId = undefined;
    lastAutoGenAt = 0;
}