import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { getWorkspacePath } from './workspacePaths';
import { generateText } from './llmClient';
import { generateAndSaveWorldForge, getDefaultGeneratorInput } from './worldForgeGenerator';
import { loadWorldForge } from './worldForge';
import { resetWorldStateFromForge } from './worldState';
import { maybeBootstrapProtagonist, quickstartFieldsToDraft } from './protagonistBootstrap';

interface QuickstartResult {
    success: boolean;
    error?: string;
}

export async function runQuickstart(userPrompt: string, overwrite: boolean): Promise<QuickstartResult> {
    const ws = getWorkspacePath();
    if (!ws) {
        return { success: false, error: 'No workspace open.' };
    }

    const worldForgePath = path.join(ws, 'world_forge.json');
    const characterPath = path.join(ws, 'character.json');
    const scenarioPath = path.join(ws, 'scenario.json');

    if (!overwrite) {
        if (fs.existsSync(worldForgePath) || fs.existsSync(characterPath)) {
            return { success: false, error: 'ALREADY_EXISTS' };
        }
    }

    vscode.window.showInformationMessage('Quickstart: Generating world and character... This may take a moment.');

    // LLM Call
    const systemPrompt = `You are a text adventure setup assistant.
The user will provide a brief idea for a world and character they want to play.
Extract and expand this into a structured JSON response with exactly these fields:
{
  "theme": "A short theme string (e.g. cyberpunk, dark fantasy, post-apocalyptic)",
  "seed": "A descriptive seed for world generation (e.g. A ruined cyberpunk city ruled by rogue AI)",
  "characterName": "A fitting name for the player character",
  "characterDescription": "A detailed description of the player character, their background, and abilities",
  "scenarioTitle": "A catchy title for the adventure",
  "scenarioObjective": "The immediate goal or starting situation for the player"
}
Output ONLY valid JSON. Do not include markdown formatting or extra text.`;

    let parsed: any = null;
    try {
        const rawResponse = await generateText(systemPrompt, userPrompt, { temperature: 0.7, maxTokens: 400 });
        if (rawResponse) {
            const cleaned = rawResponse.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
            parsed = JSON.parse(cleaned);
        }
    } catch (e) {
        console.error('Quickstart LLM Parse Error:', e);
    }

    if (!parsed) {
        // Fallback
        parsed = {
            theme: "custom",
            seed: userPrompt,
            characterName: "Player",
            characterDescription: userPrompt,
            scenarioTitle: "Quickstart Adventure",
            scenarioObjective: "Survive and explore."
        };
    }

    // 1. Generate World Forge
    const forgeInput = {
        ...getDefaultGeneratorInput(),
        worldSeed: parsed.seed,
        theme: parsed.theme
    };
    
    const forgeResult = await generateAndSaveWorldForge(forgeInput, { createBackup: true });
    if (!forgeResult.success) {
        return { success: false, error: `World generation failed: ${forgeResult.error}` };
    }

    // 2. Generate Character
    const characterData = {
        spec: "chara_card_v2",
        spec_version: "2.0",
        data: {
            name: parsed.characterName,
            description: parsed.characterDescription,
            personality: "",
            scenario: "",
            first_mes: "",
            mes_example: "",
            creator_notes: "Generated by Quickstart",
            system_prompt: "",
            post_history_instructions: "",
            tags: ["quickstart"],
            creator: "LoreRelay",
            character_version: "1.0"
        }
    };
    fs.writeFileSync(characterPath, JSON.stringify(characterData, null, 2), 'utf-8');

    // 3. Generate Scenario
    const scenarioData = {
        meta: {
            title: parsed.scenarioTitle,
            author: "LoreRelay Quickstart"
        },
        director: {
            objective: parsed.scenarioObjective,
            guidanceMode: "sandbox"
        },
        system_prompt: `You are the Game Master for a text adventure in a ${parsed.theme} setting. The player is ${parsed.characterName}: ${parsed.characterDescription}. Guide them through the world.`,
        first_message: `Welcome to ${parsed.scenarioTitle}. ${parsed.scenarioObjective}\n\nWhat do you do?`
    };
    fs.writeFileSync(scenarioPath, JSON.stringify(scenarioData, null, 2), 'utf-8');

    // 4. Initialize World State from Forge
    const forge = loadWorldForge();
    if (forge) {
        resetWorldStateFromForge(forge, true);
    }

    const draft = quickstartFieldsToDraft({
        characterName: parsed.characterName,
        characterDescription: parsed.characterDescription,
        scenarioObjective: parsed.scenarioObjective,
    });
    if (draft) {
        await maybeBootstrapProtagonist({
            quickstartDraft: draft,
            requireWorldForge: true,
            source: 'quickstart',
        });
    }

    return { success: true };
}
